#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>

report_dns_record () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  report_dns_record "$1" "www"
  report_dns_record "$1" "lb-01"
  report_dns_record "$1" "web-01"
  report_dns_record "$1" "web-02"
elif [ "$#" == 2 ]
then
  report_dns_record "$1" "$2"
fi


