#!/usr/bin/env bash
# Transfers a file from client to another server.
# Arguments: FILE IP USER SSH_KEY
#
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2":~/;
fi
