#!/usr/bin/env bash
# Install Nginx, the popular web server, on the server

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start