#!/usr/bin/env bash
# Install Nginx, the popular web server, on the server
#
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
