#!/usr/bin/env bash
# Script to configure Nginx server with a custom HTTP response header
sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i -e '/listen 80 default_server;/a rewrite ^/redirect_me https://worldsim.nousresearch.com permanent;' \
           -e '/listen 80 default_server;/{N;s/\n/\\\n/;s/$/\\\nerror_page 404 /\\\n\\tlocation = /\\\n\\t{\\n\\troot /usr/share/nginx/html;\\\n\\t\\tinternal;\\\n\\t}\\n\\tadd_header X-Served-By '$HOSTNAME'/}' \
           /etc/nginx/sites-available/default
sudo service nginx restart
